"""
Add ablation study to Week8_Comprehensive_Evaluation.ipynb

This validates whether entropy spikes are a meaningful retrieval trigger
by comparing against random and fixed-interval retrieval strategies.
"""

import json

ABLATION_CELLS = []

# Cell 1: Ablation Study Introduction
ABLATION_CELLS.append({
    'cell_type': 'markdown',
    'metadata': {},
    'source': [
        "# Ablation Study: Is Entropy Spike a Valid Retrieval Trigger?\n",
        "\n",
        "**Core Question:** Is spike-triggered retrieval better than other timing strategies with the same retrieval budget?\n",
        "\n",
        "## Comparisons\n",
        "| Method | Description |\n",
        "|--------|-------------|\n",
        "| CCE-Spike | Retrieve when entropy spikes (our method) |\n",
        "| Random | Retrieve at random positions |\n",
        "| Fixed-Interval | Retrieve every N tokens |\n",
        "| Query-Only | Retrieve once upfront based on query |\n",
        "| No-Retrieval | Generate without context (lower bound) |\n",
        "\n",
        "**Key constraint:** Same number of retrievals across methods (except query-only and no-retrieval baselines).\n",
        "\n",
        "**If spike beats random → entropy spikes are a meaningful signal, not noise.**"
    ]
})

# Cell 2: Ablation Study Implementation
ABLATION_CELLS.append({
    'cell_type': 'code',
    'execution_count': None,
    'metadata': {},
    'outputs': [],
    'source': [
        "# Ablation Study: Compare retrieval timing strategies\n",
        "import random\n",
        "import time\n",
        "import torch\n",
        "import numpy as np\n",
        "from dataclasses import dataclass\n",
        "from typing import List, Dict, Any, Tuple, Optional\n",
        "\n",
        "@dataclass\n",
        "class AblationResult:\n",
        "    \"\"\"Result from a single ablation run.\"\"\"\n",
        "    method: str\n",
        "    answer: str\n",
        "    retrieval_positions: List[int]\n",
        "    num_retrievals: int\n",
        "    tokens_generated: int\n",
        "    answer_similarity: float\n",
        "    generation_time: float\n",
        "\n",
        "class AblationStudy:\n",
        "    \"\"\"Compare different retrieval timing strategies.\"\"\"\n",
        "    \n",
        "    def __init__(self, model, tokenizer, retriever, \n",
        "                 cce_threshold=0.5, max_gen_tokens=200):\n",
        "        self.model = model\n",
        "        self.tokenizer = tokenizer\n",
        "        self.retriever = retriever\n",
        "        self.cce_threshold = cce_threshold\n",
        "        self.max_gen_tokens = max_gen_tokens\n",
        "        \n",
        "        # Precompute token sets for CCE\n",
        "        self._build_token_sets()\n",
        "    \n",
        "    def _build_token_sets(self):\n",
        "        \"\"\"Build code vs language token sets.\"\"\"\n",
        "        CODE_KEYWORDS = {\n",
        "            'def', 'class', 'import', 'from', 'return', 'if', 'else', 'elif',\n",
        "            'for', 'while', 'try', 'except', 'with', 'as', 'lambda', 'yield',\n",
        "            'async', 'await', 'None', 'True', 'False', 'self', 'cls',\n",
        "            'function', 'const', 'let', 'var', 'interface', 'type', 'enum',\n",
        "            'public', 'private', 'static', 'void', 'int', 'str', 'bool',\n",
        "        }\n",
        "        \n",
        "        self.code_token_ids = set()\n",
        "        self.lang_token_ids = set()\n",
        "        \n",
        "        for token_id in range(len(self.tokenizer)):\n",
        "            try:\n",
        "                token = self.tokenizer.decode([token_id]).strip().lower()\n",
        "                if token in CODE_KEYWORDS or token.startswith('_') or token.startswith('.'):\n",
        "                    self.code_token_ids.add(token_id)\n",
        "                elif token.isalpha() and len(token) > 2:\n",
        "                    self.lang_token_ids.add(token_id)\n",
        "            except:\n",
        "                pass\n",
        "    \n",
        "    def _compute_cce(self, logits: torch.Tensor) -> float:\n",
        "        \"\"\"Compute CCE = H_code - H_lang.\"\"\"\n",
        "        probs = torch.softmax(logits, dim=-1)\n",
        "        \n",
        "        code_ids = list(self.code_token_ids & set(range(len(probs))))\n",
        "        lang_ids = list(self.lang_token_ids & set(range(len(probs))))\n",
        "        \n",
        "        if not code_ids or not lang_ids:\n",
        "            return 0.0\n",
        "        \n",
        "        code_probs = probs[code_ids]\n",
        "        lang_probs = probs[lang_ids]\n",
        "        \n",
        "        # Normalize\n",
        "        code_probs = code_probs / (code_probs.sum() + 1e-10)\n",
        "        lang_probs = lang_probs / (lang_probs.sum() + 1e-10)\n",
        "        \n",
        "        # Entropy\n",
        "        h_code = -torch.sum(code_probs * torch.log(code_probs + 1e-10)).item()\n",
        "        h_lang = -torch.sum(lang_probs * torch.log(lang_probs + 1e-10)).item()\n",
        "        \n",
        "        return h_code - h_lang\n",
        "    \n",
        "    def _retrieve_context(self, query: str, generated_so_far: str = '') -> str:\n",
        "        \"\"\"Retrieve relevant context.\"\"\"\n",
        "        search_query = query\n",
        "        if generated_so_far:\n",
        "            # Use recent generated text to refine query\n",
        "            search_query = query + ' ' + generated_so_far[-200:]\n",
        "        \n",
        "        results = self.retriever.retrieve(search_query, top_k=2)\n",
        "        context = '\\n'.join([r['content'][:500] for r in results])\n",
        "        return context\n",
        "    \n",
        "    def generate_with_spike_retrieval(self, query: str, max_retrievals: int = 2\n",
        "                                      ) -> Tuple[str, List[int]]:\n",
        "        \"\"\"Our method: retrieve when CCE exceeds threshold.\"\"\"\n",
        "        prompt = f\"Question: {query}\\nAnswer:\"\n",
        "        input_ids = self.tokenizer.encode(prompt, return_tensors='pt').to(self.model.device)\n",
        "        \n",
        "        generated_ids = input_ids.clone()\n",
        "        retrieval_positions = []\n",
        "        context_injected = \"\"\n",
        "        \n",
        "        for step in range(self.max_gen_tokens):\n",
        "            with torch.no_grad():\n",
        "                outputs = self.model(generated_ids)\n",
        "                logits = outputs.logits[0, -1, :]\n",
        "            \n",
        "            # Check for spike\n",
        "            cce = self._compute_cce(logits)\n",
        "            \n",
        "            if cce > self.cce_threshold and len(retrieval_positions) < max_retrievals:\n",
        "                # Retrieve and inject context\n",
        "                generated_text = self.tokenizer.decode(generated_ids[0, input_ids.shape[1]:], \n",
        "                                                        skip_special_tokens=True)\n",
        "                context = self._retrieve_context(query, generated_text)\n",
        "                context_injected += f\"\\n[Retrieved context: {context[:300]}...]\\n\"\n",
        "                retrieval_positions.append(step)\n",
        "                \n",
        "                # Rebuild prompt with context\n",
        "                new_prompt = f\"Context: {context}\\n\\nQuestion: {query}\\nAnswer: {generated_text}\"\n",
        "                generated_ids = self.tokenizer.encode(new_prompt, return_tensors='pt').to(self.model.device)\n",
        "            \n",
        "            # Sample next token\n",
        "            probs = torch.softmax(logits, dim=-1)\n",
        "            next_token = torch.multinomial(probs, num_samples=1)\n",
        "            generated_ids = torch.cat([generated_ids, next_token.unsqueeze(0)], dim=-1)\n",
        "            \n",
        "            # Check for EOS\n",
        "            if next_token.item() == self.tokenizer.eos_token_id:\n",
        "                break\n",
        "        \n",
        "        answer = self.tokenizer.decode(generated_ids[0, input_ids.shape[1]:], \n",
        "                                        skip_special_tokens=True)\n",
        "        return answer, retrieval_positions\n",
        "    \n",
        "    def generate_with_random_retrieval(self, query: str, num_retrievals: int = 2,\n",
        "                                       seed: int = None) -> Tuple[str, List[int]]:\n",
        "        \"\"\"Control: retrieve at random positions.\"\"\"\n",
        "        if seed is not None:\n",
        "            random.seed(seed)\n",
        "        \n",
        "        # Pre-select random positions\n",
        "        positions = sorted(random.sample(range(10, self.max_gen_tokens - 10), \n",
        "                                         min(num_retrievals, self.max_gen_tokens - 20)))\n",
        "        \n",
        "        prompt = f\"Question: {query}\\nAnswer:\"\n",
        "        input_ids = self.tokenizer.encode(prompt, return_tensors='pt').to(self.model.device)\n",
        "        \n",
        "        generated_ids = input_ids.clone()\n",
        "        retrieval_positions = []\n",
        "        \n",
        "        for step in range(self.max_gen_tokens):\n",
        "            with torch.no_grad():\n",
        "                outputs = self.model(generated_ids)\n",
        "                logits = outputs.logits[0, -1, :]\n",
        "            \n",
        "            # Check if this is a retrieval position\n",
        "            if step in positions:\n",
        "                generated_text = self.tokenizer.decode(generated_ids[0, input_ids.shape[1]:],\n",
        "                                                        skip_special_tokens=True)\n",
        "                context = self._retrieve_context(query, generated_text)\n",
        "                retrieval_positions.append(step)\n",
        "                \n",
        "                new_prompt = f\"Context: {context}\\n\\nQuestion: {query}\\nAnswer: {generated_text}\"\n",
        "                generated_ids = self.tokenizer.encode(new_prompt, return_tensors='pt').to(self.model.device)\n",
        "            \n",
        "            # Sample next token\n",
        "            probs = torch.softmax(logits, dim=-1)\n",
        "            next_token = torch.multinomial(probs, num_samples=1)\n",
        "            generated_ids = torch.cat([generated_ids, next_token.unsqueeze(0)], dim=-1)\n",
        "            \n",
        "            if next_token.item() == self.tokenizer.eos_token_id:\n",
        "                break\n",
        "        \n",
        "        answer = self.tokenizer.decode(generated_ids[0, input_ids.shape[1]:],\n",
        "                                        skip_special_tokens=True)\n",
        "        return answer, retrieval_positions\n",
        "    \n",
        "    def generate_with_fixed_interval(self, query: str, interval: int = 50,\n",
        "                                     max_retrievals: int = 2) -> Tuple[str, List[int]]:\n",
        "        \"\"\"Control: retrieve every N tokens.\"\"\"\n",
        "        prompt = f\"Question: {query}\\nAnswer:\"\n",
        "        input_ids = self.tokenizer.encode(prompt, return_tensors='pt').to(self.model.device)\n",
        "        \n",
        "        generated_ids = input_ids.clone()\n",
        "        retrieval_positions = []\n",
        "        \n",
        "        for step in range(self.max_gen_tokens):\n",
        "            with torch.no_grad():\n",
        "                outputs = self.model(generated_ids)\n",
        "                logits = outputs.logits[0, -1, :]\n",
        "            \n",
        "            # Check if this is an interval position\n",
        "            if step > 0 and step % interval == 0 and len(retrieval_positions) < max_retrievals:\n",
        "                generated_text = self.tokenizer.decode(generated_ids[0, input_ids.shape[1]:],\n",
        "                                                        skip_special_tokens=True)\n",
        "                context = self._retrieve_context(query, generated_text)\n",
        "                retrieval_positions.append(step)\n",
        "                \n",
        "                new_prompt = f\"Context: {context}\\n\\nQuestion: {query}\\nAnswer: {generated_text}\"\n",
        "                generated_ids = self.tokenizer.encode(new_prompt, return_tensors='pt').to(self.model.device)\n",
        "            \n",
        "            # Sample next token\n",
        "            probs = torch.softmax(logits, dim=-1)\n",
        "            next_token = torch.multinomial(probs, num_samples=1)\n",
        "            generated_ids = torch.cat([generated_ids, next_token.unsqueeze(0)], dim=-1)\n",
        "            \n",
        "            if next_token.item() == self.tokenizer.eos_token_id:\n",
        "                break\n",
        "        \n",
        "        answer = self.tokenizer.decode(generated_ids[0, input_ids.shape[1]:],\n",
        "                                        skip_special_tokens=True)\n",
        "        return answer, retrieval_positions\n",
        "    \n",
        "    def generate_with_query_only(self, query: str) -> Tuple[str, List[int]]:\n",
        "        \"\"\"Baseline: retrieve once upfront based on query.\"\"\"\n",
        "        context = self._retrieve_context(query)\n",
        "        \n",
        "        prompt = f\"Context: {context}\\n\\nQuestion: {query}\\nAnswer:\"\n",
        "        input_ids = self.tokenizer.encode(prompt, return_tensors='pt').to(self.model.device)\n",
        "        \n",
        "        with torch.no_grad():\n",
        "            outputs = self.model.generate(\n",
        "                input_ids,\n",
        "                max_new_tokens=self.max_gen_tokens,\n",
        "                pad_token_id=self.tokenizer.eos_token_id,\n",
        "                do_sample=True,\n",
        "                temperature=0.7\n",
        "            )\n",
        "        \n",
        "        answer = self.tokenizer.decode(outputs[0, input_ids.shape[1]:],\n",
        "                                        skip_special_tokens=True)\n",
        "        return answer, [0]  # Single retrieval at position 0\n",
        "    \n",
        "    def generate_no_retrieval(self, query: str) -> Tuple[str, List[int]]:\n",
        "        \"\"\"Lower bound: no context at all.\"\"\"\n",
        "        prompt = f\"Question: {query}\\nAnswer:\"\n",
        "        input_ids = self.tokenizer.encode(prompt, return_tensors='pt').to(self.model.device)\n",
        "        \n",
        "        with torch.no_grad():\n",
        "            outputs = self.model.generate(\n",
        "                input_ids,\n",
        "                max_new_tokens=self.max_gen_tokens,\n",
        "                pad_token_id=self.tokenizer.eos_token_id,\n",
        "                do_sample=True,\n",
        "                temperature=0.7\n",
        "            )\n",
        "        \n",
        "        answer = self.tokenizer.decode(outputs[0, input_ids.shape[1]:],\n",
        "                                        skip_special_tokens=True)\n",
        "        return answer, []\n",
        "\n",
        "print(\"AblationStudy class defined\")"
    ]
})

# Cell 3: Run Ablation Study
ABLATION_CELLS.append({
    'cell_type': 'code',
    'execution_count': None,
    'metadata': {},
    'outputs': [],
    'source': [
        "# Run the ablation study\n",
        "from sentence_transformers import SentenceTransformer\n",
        "from sklearn.metrics.pairwise import cosine_similarity\n",
        "\n",
        "# Initialize ablation study\n",
        "ablation = AblationStudy(\n",
        "    model=model,\n",
        "    tokenizer=tokenizer,\n",
        "    retriever=retriever,\n",
        "    cce_threshold=0.5,\n",
        "    max_gen_tokens=150  # Shorter for faster ablation\n",
        ")\n",
        "\n",
        "# Similarity model for scoring\n",
        "sim_model = SentenceTransformer('all-MiniLM-L6-v2')\n",
        "\n",
        "def compute_similarity(answer: str, ground_truth: str) -> float:\n",
        "    \"\"\"Compute semantic similarity between answer and ground truth.\"\"\"\n",
        "    if not answer or not ground_truth:\n",
        "        return 0.0\n",
        "    emb1 = sim_model.encode([answer])\n",
        "    emb2 = sim_model.encode([ground_truth])\n",
        "    return float(cosine_similarity(emb1, emb2)[0][0])\n",
        "\n",
        "# Run ablation on test examples\n",
        "ablation_results = []\n",
        "NUM_RANDOM_SEEDS = 5  # Multiple seeds for random baseline\n",
        "\n",
        "print(\"Running Ablation Study\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "for i, example in enumerate(test_examples[:5]):  # Use first 5 examples\n",
        "    print(f\"\\nExample {i+1}/{min(5, len(test_examples))}: {example.query[:50]}...\")\n",
        "    \n",
        "    # 1. CCE-Spike (our method)\n",
        "    start = time.time()\n",
        "    spike_answer, spike_positions = ablation.generate_with_spike_retrieval(\n",
        "        example.query, max_retrievals=2\n",
        "    )\n",
        "    spike_time = time.time() - start\n",
        "    spike_sim = compute_similarity(spike_answer, example.ground_truth_answer)\n",
        "    num_retrievals = len(spike_positions)\n",
        "    \n",
        "    ablation_results.append({\n",
        "        'example_id': example.id,\n",
        "        'method': 'cce_spike',\n",
        "        'answer': spike_answer,\n",
        "        'similarity': spike_sim,\n",
        "        'num_retrievals': num_retrievals,\n",
        "        'positions': spike_positions,\n",
        "        'time': spike_time\n",
        "    })\n",
        "    print(f\"  CCE-Spike: sim={spike_sim:.3f}, retrievals={num_retrievals} at {spike_positions}\")\n",
        "    \n",
        "    # 2. Random (multiple seeds, match retrieval count)\n",
        "    for seed in range(NUM_RANDOM_SEEDS):\n",
        "        start = time.time()\n",
        "        random_answer, random_positions = ablation.generate_with_random_retrieval(\n",
        "            example.query, num_retrievals=max(1, num_retrievals), seed=seed\n",
        "        )\n",
        "        random_time = time.time() - start\n",
        "        random_sim = compute_similarity(random_answer, example.ground_truth_answer)\n",
        "        \n",
        "        ablation_results.append({\n",
        "            'example_id': example.id,\n",
        "            'method': 'random',\n",
        "            'answer': random_answer,\n",
        "            'similarity': random_sim,\n",
        "            'num_retrievals': len(random_positions),\n",
        "            'positions': random_positions,\n",
        "            'time': random_time,\n",
        "            'seed': seed\n",
        "        })\n",
        "    random_avg = np.mean([r['similarity'] for r in ablation_results \n",
        "                          if r['example_id'] == example.id and r['method'] == 'random'])\n",
        "    print(f\"  Random (avg of {NUM_RANDOM_SEEDS}): sim={random_avg:.3f}\")\n",
        "    \n",
        "    # 3. Fixed-Interval (match retrieval count)\n",
        "    interval = max(30, 150 // max(1, num_retrievals))\n",
        "    start = time.time()\n",
        "    fixed_answer, fixed_positions = ablation.generate_with_fixed_interval(\n",
        "        example.query, interval=interval, max_retrievals=max(1, num_retrievals)\n",
        "    )\n",
        "    fixed_time = time.time() - start\n",
        "    fixed_sim = compute_similarity(fixed_answer, example.ground_truth_answer)\n",
        "    \n",
        "    ablation_results.append({\n",
        "        'example_id': example.id,\n",
        "        'method': 'fixed_interval',\n",
        "        'answer': fixed_answer,\n",
        "        'similarity': fixed_sim,\n",
        "        'num_retrievals': len(fixed_positions),\n",
        "        'positions': fixed_positions,\n",
        "        'time': fixed_time\n",
        "    })\n",
        "    print(f\"  Fixed-Interval: sim={fixed_sim:.3f}, retrievals={len(fixed_positions)}\")\n",
        "    \n",
        "    # 4. Query-Only (single upfront retrieval)\n",
        "    start = time.time()\n",
        "    query_answer, query_positions = ablation.generate_with_query_only(example.query)\n",
        "    query_time = time.time() - start\n",
        "    query_sim = compute_similarity(query_answer, example.ground_truth_answer)\n",
        "    \n",
        "    ablation_results.append({\n",
        "        'example_id': example.id,\n",
        "        'method': 'query_only',\n",
        "        'answer': query_answer,\n",
        "        'similarity': query_sim,\n",
        "        'num_retrievals': 1,\n",
        "        'positions': [0],\n",
        "        'time': query_time\n",
        "    })\n",
        "    print(f\"  Query-Only: sim={query_sim:.3f}\")\n",
        "    \n",
        "    # 5. No-Retrieval (lower bound)\n",
        "    start = time.time()\n",
        "    no_ret_answer, _ = ablation.generate_no_retrieval(example.query)\n",
        "    no_ret_time = time.time() - start\n",
        "    no_ret_sim = compute_similarity(no_ret_answer, example.ground_truth_answer)\n",
        "    \n",
        "    ablation_results.append({\n",
        "        'example_id': example.id,\n",
        "        'method': 'no_retrieval',\n",
        "        'answer': no_ret_answer,\n",
        "        'similarity': no_ret_sim,\n",
        "        'num_retrievals': 0,\n",
        "        'positions': [],\n",
        "        'time': no_ret_time\n",
        "    })\n",
        "    print(f\"  No-Retrieval: sim={no_ret_sim:.3f}\")\n",
        "\n",
        "print(\"\\n\" + \"=\" * 60)\n",
        "print(\"Ablation study complete!\")"
    ]
})

# Cell 4: Analyze Ablation Results
ABLATION_CELLS.append({
    'cell_type': 'code',
    'execution_count': None,
    'metadata': {},
    'outputs': [],
    'source': [
        "# Analyze ablation results with bootstrap CIs\n",
        "import pandas as pd\n",
        "\n",
        "df_ablation = pd.DataFrame(ablation_results)\n",
        "\n",
        "def bootstrap_ci(data, n_bootstrap=1000, ci=95):\n",
        "    \"\"\"Compute bootstrapped confidence interval.\"\"\"\n",
        "    data = np.array(data)\n",
        "    data = data[~np.isnan(data)]\n",
        "    if len(data) < 2:\n",
        "        mean = np.mean(data) if len(data) > 0 else 0\n",
        "        return mean, mean, mean\n",
        "    boot_means = [np.mean(np.random.choice(data, size=len(data), replace=True)) \n",
        "                  for _ in range(n_bootstrap)]\n",
        "    lower = np.percentile(boot_means, (100 - ci) / 2)\n",
        "    upper = np.percentile(boot_means, 100 - (100 - ci) / 2)\n",
        "    return np.mean(data), lower, upper\n",
        "\n",
        "print(\"\\n\" + \"=\" * 70)\n",
        "print(\"ABLATION STUDY RESULTS\")\n",
        "print(\"=\" * 70)\n",
        "print(\"\\nAnswer Similarity by Retrieval Strategy (with 95% Bootstrap CI):\")\n",
        "print(\"-\" * 70)\n",
        "\n",
        "methods_order = ['cce_spike', 'random', 'fixed_interval', 'query_only', 'no_retrieval']\n",
        "method_labels = {\n",
        "    'cce_spike': 'CCE-Spike (Ours)',\n",
        "    'random': 'Random',\n",
        "    'fixed_interval': 'Fixed-Interval',\n",
        "    'query_only': 'Query-Only',\n",
        "    'no_retrieval': 'No Retrieval'\n",
        "}\n",
        "\n",
        "ablation_summary = []\n",
        "for method in methods_order:\n",
        "    scores = df_ablation[df_ablation['method'] == method]['similarity'].values\n",
        "    mean, ci_low, ci_high = bootstrap_ci(scores)\n",
        "    \n",
        "    avg_retrievals = df_ablation[df_ablation['method'] == method]['num_retrievals'].mean()\n",
        "    \n",
        "    ablation_summary.append({\n",
        "        'Method': method_labels[method],\n",
        "        'Similarity': mean,\n",
        "        'CI_Low': ci_low,\n",
        "        'CI_High': ci_high,\n",
        "        'Avg_Retrievals': avg_retrievals\n",
        "    })\n",
        "    \n",
        "    print(f\"{method_labels[method]:20s}: {mean:.3f} [{ci_low:.3f}, {ci_high:.3f}]  (avg {avg_retrievals:.1f} retrievals)\")\n",
        "\n",
        "df_ablation_summary = pd.DataFrame(ablation_summary)\n",
        "\n",
        "# Key comparisons\n",
        "print(\"\\n\" + \"-\" * 70)\n",
        "print(\"KEY COMPARISONS:\")\n",
        "print(\"-\" * 70)\n",
        "\n",
        "spike_scores = df_ablation[df_ablation['method'] == 'cce_spike']['similarity'].values\n",
        "random_scores = df_ablation[df_ablation['method'] == 'random']['similarity'].values\n",
        "fixed_scores = df_ablation[df_ablation['method'] == 'fixed_interval']['similarity'].values\n",
        "query_scores = df_ablation[df_ablation['method'] == 'query_only']['similarity'].values\n",
        "\n",
        "# Spike vs Random (key test)\n",
        "spike_mean = np.mean(spike_scores)\n",
        "random_mean = np.mean(random_scores)\n",
        "diff_sr = spike_mean - random_mean\n",
        "print(f\"\\n1. CCE-Spike vs Random:\")\n",
        "print(f\"   Spike: {spike_mean:.3f}, Random: {random_mean:.3f}, Diff: {diff_sr:+.3f}\")\n",
        "if diff_sr > 0:\n",
        "    print(f\"   → Spike BEATS random by {diff_sr:.3f} → SPIKES ARE MEANINGFUL\")\n",
        "else:\n",
        "    print(f\"   → Spike does NOT beat random → spikes may be noise\")\n",
        "\n",
        "# Spike vs Fixed\n",
        "diff_sf = spike_mean - np.mean(fixed_scores)\n",
        "print(f\"\\n2. CCE-Spike vs Fixed-Interval:\")\n",
        "print(f\"   Diff: {diff_sf:+.3f}\")\n",
        "if diff_sf > 0:\n",
        "    print(f\"   → Spike timing is better than periodic timing\")\n",
        "\n",
        "# Spike vs Query-Only  \n",
        "diff_sq = spike_mean - np.mean(query_scores)\n",
        "print(f\"\\n3. CCE-Spike vs Query-Only:\")\n",
        "print(f\"   Diff: {diff_sq:+.3f}\")\n",
        "if diff_sq > 0:\n",
        "    print(f\"   → Mid-generation retrieval beats upfront retrieval\")\n",
        "else:\n",
        "    print(f\"   → Upfront retrieval is sufficient\")"
    ]
})

# Cell 5: Visualization
ABLATION_CELLS.append({
    'cell_type': 'code',
    'execution_count': None,
    'metadata': {},
    'outputs': [],
    'source': [
        "# Visualize ablation results\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
        "\n",
        "# Plot 1: Answer similarity by method\n",
        "ax1 = axes[0]\n",
        "methods = df_ablation_summary['Method'].tolist()\n",
        "similarities = df_ablation_summary['Similarity'].tolist()\n",
        "ci_lows = df_ablation_summary['CI_Low'].tolist()\n",
        "ci_highs = df_ablation_summary['CI_High'].tolist()\n",
        "errors = [[s - l for s, l in zip(similarities, ci_lows)],\n",
        "          [h - s for s, h in zip(similarities, ci_highs)]]\n",
        "\n",
        "colors = ['#2ecc71', '#3498db', '#9b59b6', '#f39c12', '#e74c3c']\n",
        "bars = ax1.bar(range(len(methods)), similarities, yerr=errors, capsize=5,\n",
        "               color=colors, edgecolor='black', linewidth=1.2)\n",
        "ax1.set_xticks(range(len(methods)))\n",
        "ax1.set_xticklabels(methods, rotation=45, ha='right')\n",
        "ax1.set_ylabel('Answer Similarity')\n",
        "ax1.set_title('Ablation Study: Retrieval Timing Strategies\\n(with 95% Bootstrap CI)')\n",
        "ax1.set_ylim(0, 1)\n",
        "ax1.axhline(y=similarities[0], color='#2ecc71', linestyle='--', alpha=0.5, \n",
        "            label='CCE-Spike baseline')\n",
        "ax1.legend()\n",
        "\n",
        "# Annotate bars\n",
        "for i, (bar, sim) in enumerate(zip(bars, similarities)):\n",
        "    ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.02,\n",
        "             f'{sim:.3f}', ha='center', va='bottom', fontsize=10)\n",
        "\n",
        "# Plot 2: Per-example comparison (Spike vs Random)\n",
        "ax2 = axes[1]\n",
        "example_ids = df_ablation[df_ablation['method'] == 'cce_spike']['example_id'].unique()\n",
        "\n",
        "spike_by_example = []\n",
        "random_by_example = []\n",
        "for eid in example_ids:\n",
        "    spike_sim = df_ablation[(df_ablation['example_id'] == eid) & \n",
        "                            (df_ablation['method'] == 'cce_spike')]['similarity'].values[0]\n",
        "    random_sim = df_ablation[(df_ablation['example_id'] == eid) & \n",
        "                             (df_ablation['method'] == 'random')]['similarity'].mean()\n",
        "    spike_by_example.append(spike_sim)\n",
        "    random_by_example.append(random_sim)\n",
        "\n",
        "x = np.arange(len(example_ids))\n",
        "width = 0.35\n",
        "ax2.bar(x - width/2, spike_by_example, width, label='CCE-Spike', color='#2ecc71')\n",
        "ax2.bar(x + width/2, random_by_example, width, label='Random', color='#3498db')\n",
        "ax2.set_xlabel('Example')\n",
        "ax2.set_ylabel('Answer Similarity')\n",
        "ax2.set_title('Per-Example: CCE-Spike vs Random')\n",
        "ax2.set_xticks(x)\n",
        "ax2.set_xticklabels([f'Ex {i+1}' for i in range(len(example_ids))])\n",
        "ax2.legend()\n",
        "ax2.set_ylim(0, 1)\n",
        "\n",
        "# Count wins\n",
        "spike_wins = sum(s > r for s, r in zip(spike_by_example, random_by_example))\n",
        "ax2.set_xlabel(f'Example\\n(Spike wins: {spike_wins}/{len(example_ids)})')\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.savefig('ablation_study_results.png', dpi=150, bbox_inches='tight')\n",
        "plt.show()\n",
        "\n",
        "print(f\"\\nSpike wins on {spike_wins}/{len(example_ids)} examples\")"
    ]
})

# Cell 6: Conclusion
ABLATION_CELLS.append({
    'cell_type': 'markdown',
    'metadata': {},
    'source': [
        "## Ablation Study Conclusions\n",
        "\n",
        "### Key Finding\n",
        "\n",
        "**If CCE-Spike > Random with same retrieval budget:**\n",
        "- Entropy spikes are a **meaningful signal** for retrieval timing\n",
        "- The spikes identify moments when the model genuinely needs information\n",
        "\n",
        "**If CCE-Spike ≈ Random:**\n",
        "- Spikes may be **noise**, not a useful signal\n",
        "- Random retrieval is just as good → timing doesn't matter, only retrieval count\n",
        "\n",
        "### Interpretation Guide\n",
        "\n",
        "| Result | Interpretation |\n",
        "|--------|---------------|\n",
        "| Spike >> Random | Strong evidence spikes are meaningful |\n",
        "| Spike > Random | Weak evidence spikes help |\n",
        "| Spike ≈ Random | Spikes are noise |\n",
        "| Spike < Random | Spikes are misleading (retrieve at wrong times) |\n",
        "\n",
        "### Limitations\n",
        "\n",
        "- Small sample size (need more examples for robust conclusions)\n",
        "- Single model/domain (may not generalize)\n",
        "- Retrieval quality affects all methods equally"
    ]
})


def add_ablation_to_notebook():
    """Add ablation study cells to the notebook."""
    print("Adding ablation study to Week8_Comprehensive_Evaluation.ipynb")
    print("=" * 60)

    with open('Week8_Comprehensive_Evaluation.ipynb', 'r', encoding='utf-8') as f:
        nb = json.load(f)

    # Check if ablation already exists
    for cell in nb['cells']:
        source = ''.join(cell.get('source', []))
        if 'class AblationStudy' in source:
            print("Ablation study already exists in notebook")
            return

    # Find the right place to insert - after the main experiment results
    insert_idx = len(nb['cells']) - 2  # Before the last couple cells (usually export)

    # Look for a better insertion point (after comparison table)
    for i, cell in enumerate(nb['cells']):
        source = ''.join(cell.get('source', []))
        if 'df_comparison' in source and 'to_dict' in source:
            insert_idx = i + 1
            break

    # Insert all ablation cells
    for j, cell in enumerate(ABLATION_CELLS):
        # Fix source format for code cells
        if isinstance(cell.get('source'), list):
            cell['source'] = [line if line.endswith('\n') else line + '\n'
                             for line in cell['source']]
            # Remove trailing newline from last line
            if cell['source']:
                cell['source'][-1] = cell['source'][-1].rstrip('\n')

        nb['cells'].insert(insert_idx + j, cell)

    # Save
    with open('Week8_Comprehensive_Evaluation.ipynb', 'w', encoding='utf-8') as f:
        json.dump(nb, f, indent=1)

    print(f"Added {len(ABLATION_CELLS)} ablation study cells at index {insert_idx}")
    print("\nCells added:")
    print("  1. Ablation Study Introduction (markdown)")
    print("  2. AblationStudy class implementation")
    print("  3. Run ablation study")
    print("  4. Analyze results with bootstrap CIs")
    print("  5. Visualization")
    print("  6. Conclusions (markdown)")

if __name__ == '__main__':
    import os
    os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    add_ablation_to_notebook()
