"""
Fix ablation study to use the ACTUAL Real CCE implementation from the notebook,
not a simplified version.
"""

import json

# New ablation study cells that use the existing Real CCE classes
ABLATION_CELLS = []

# Cell 1: Ablation Study Introduction (keep same)
ABLATION_CELLS.append({
    'cell_type': 'markdown',
    'metadata': {},
    'source': [
        "# Ablation Study: Is Entropy Spike a Valid Retrieval Trigger?\n",
        "\n",
        "**Core Question:** Is spike-triggered retrieval better than other timing strategies with the same retrieval budget?\n",
        "\n",
        "## Comparisons\n",
        "| Method | Description |\n",
        "|--------|-------------|\n",
        "| CCE-Spike (Real CCE) | Retrieve when CCE spikes - uses actual RealCCEMultiHopRetriever |\n",
        "| Random | Retrieve at random positions |\n",
        "| Fixed-Interval | Retrieve every N tokens |\n",
        "| Query-Only | Retrieve once upfront based on query |\n",
        "| No-Retrieval | Generate without context (lower bound) |\n",
        "\n",
        "**Key constraint:** Same number of retrievals across methods.\n",
        "\n",
        "**If CCE-Spike beats random → entropy spikes are a meaningful signal, not noise.**"
    ]
})

# Cell 2: Ablation baselines (Random, Fixed-Interval) - these need custom implementation
ABLATION_CELLS.append({
    'cell_type': 'code',
    'execution_count': None,
    'metadata': {},
    'outputs': [],
    'source': [
        "# Ablation Study Baselines\n",
        "# These implement alternative retrieval timing strategies for comparison\n",
        "\n",
        "import random\n",
        "import time\n",
        "import torch\n",
        "import numpy as np\n",
        "from dataclasses import dataclass\n",
        "from typing import List, Dict, Any, Tuple\n",
        "\n",
        "@dataclass\n",
        "class AblationResult:\n",
        "    \"\"\"Result from a single ablation run.\"\"\"\n",
        "    method: str\n",
        "    answer: str\n",
        "    retrieval_positions: List[int]\n",
        "    num_retrievals: int\n",
        "    similarity: float\n",
        "    generation_time: float\n",
        "\n",
        "\n",
        "class RandomRetrievalGenerator:\n",
        "    \"\"\"\n",
        "    Baseline: Retrieve at random positions during generation.\n",
        "    Uses same retriever as Real CCE for fair comparison.\n",
        "    \"\"\"\n",
        "    \n",
        "    def __init__(self, model, tokenizer, retriever, max_gen_tokens=200):\n",
        "        self.model = model\n",
        "        self.tokenizer = tokenizer\n",
        "        self.retriever = retriever\n",
        "        self.max_gen_tokens = max_gen_tokens\n",
        "    \n",
        "    def generate(self, query: str, num_retrievals: int = 2, seed: int = None\n",
        "                ) -> Tuple[str, List[int], float]:\n",
        "        \"\"\"Generate with retrieval at random positions.\"\"\"\n",
        "        if seed is not None:\n",
        "            random.seed(seed)\n",
        "        \n",
        "        start_time = time.time()\n",
        "        \n",
        "        # Pre-select random positions (avoid very beginning/end)\n",
        "        safe_range = range(15, self.max_gen_tokens - 15)\n",
        "        positions = sorted(random.sample(list(safe_range), \n",
        "                                         min(num_retrievals, len(safe_range))))\n",
        "        \n",
        "        prompt = f\"Question: {query}\\nAnswer:\"\n",
        "        input_ids = self.tokenizer.encode(prompt, return_tensors='pt').to(self.model.device)\n",
        "        initial_len = input_ids.shape[1]\n",
        "        \n",
        "        generated_ids = input_ids.clone()\n",
        "        retrieval_positions = []\n",
        "        current_context = \"\"\n",
        "        \n",
        "        for step in range(self.max_gen_tokens):\n",
        "            # Check if this is a retrieval position\n",
        "            if step in positions:\n",
        "                generated_text = self.tokenizer.decode(\n",
        "                    generated_ids[0, initial_len:], skip_special_tokens=True\n",
        "                )\n",
        "                \n",
        "                # Retrieve using same retriever as Real CCE\n",
        "                search_query = f\"{query} {generated_text[-100:]}\"\n",
        "                results = self.retriever.retrieve(search_query, top_k=2)\n",
        "                context = '\\n'.join([r['content'][:500] for r in results])\n",
        "                current_context = context\n",
        "                retrieval_positions.append(step)\n",
        "                \n",
        "                # Rebuild prompt with context\n",
        "                new_prompt = f\"Context:\\n{context}\\n\\nQuestion: {query}\\nAnswer: {generated_text}\"\n",
        "                generated_ids = self.tokenizer.encode(\n",
        "                    new_prompt, return_tensors='pt', truncation=True, max_length=2048\n",
        "                ).to(self.model.device)\n",
        "                initial_len = len(self.tokenizer.encode(f\"Context:\\n{context}\\n\\nQuestion: {query}\\nAnswer:\"))\n",
        "            \n",
        "            # Generate next token\n",
        "            with torch.no_grad():\n",
        "                outputs = self.model(generated_ids)\n",
        "                logits = outputs.logits[0, -1, :]\n",
        "            \n",
        "            probs = torch.softmax(logits, dim=-1)\n",
        "            next_token = torch.multinomial(probs, num_samples=1)\n",
        "            generated_ids = torch.cat([generated_ids, next_token.unsqueeze(0)], dim=-1)\n",
        "            \n",
        "            if next_token.item() == self.tokenizer.eos_token_id:\n",
        "                break\n",
        "        \n",
        "        answer = self.tokenizer.decode(generated_ids[0, initial_len:], skip_special_tokens=True)\n",
        "        gen_time = time.time() - start_time\n",
        "        \n",
        "        return answer, retrieval_positions, gen_time\n",
        "\n",
        "\n",
        "class FixedIntervalGenerator:\n",
        "    \"\"\"\n",
        "    Baseline: Retrieve every N tokens during generation.\n",
        "    Uses same retriever as Real CCE for fair comparison.\n",
        "    \"\"\"\n",
        "    \n",
        "    def __init__(self, model, tokenizer, retriever, max_gen_tokens=200):\n",
        "        self.model = model\n",
        "        self.tokenizer = tokenizer\n",
        "        self.retriever = retriever\n",
        "        self.max_gen_tokens = max_gen_tokens\n",
        "    \n",
        "    def generate(self, query: str, interval: int = 50, max_retrievals: int = 2\n",
        "                ) -> Tuple[str, List[int], float]:\n",
        "        \"\"\"Generate with retrieval at fixed intervals.\"\"\"\n",
        "        start_time = time.time()\n",
        "        \n",
        "        prompt = f\"Question: {query}\\nAnswer:\"\n",
        "        input_ids = self.tokenizer.encode(prompt, return_tensors='pt').to(self.model.device)\n",
        "        initial_len = input_ids.shape[1]\n",
        "        \n",
        "        generated_ids = input_ids.clone()\n",
        "        retrieval_positions = []\n",
        "        \n",
        "        for step in range(self.max_gen_tokens):\n",
        "            # Check if this is an interval position\n",
        "            if step > 0 and step % interval == 0 and len(retrieval_positions) < max_retrievals:\n",
        "                generated_text = self.tokenizer.decode(\n",
        "                    generated_ids[0, initial_len:], skip_special_tokens=True\n",
        "                )\n",
        "                \n",
        "                # Retrieve\n",
        "                search_query = f\"{query} {generated_text[-100:]}\"\n",
        "                results = self.retriever.retrieve(search_query, top_k=2)\n",
        "                context = '\\n'.join([r['content'][:500] for r in results])\n",
        "                retrieval_positions.append(step)\n",
        "                \n",
        "                # Rebuild prompt with context\n",
        "                new_prompt = f\"Context:\\n{context}\\n\\nQuestion: {query}\\nAnswer: {generated_text}\"\n",
        "                generated_ids = self.tokenizer.encode(\n",
        "                    new_prompt, return_tensors='pt', truncation=True, max_length=2048\n",
        "                ).to(self.model.device)\n",
        "                initial_len = len(self.tokenizer.encode(f\"Context:\\n{context}\\n\\nQuestion: {query}\\nAnswer:\"))\n",
        "            \n",
        "            # Generate next token\n",
        "            with torch.no_grad():\n",
        "                outputs = self.model(generated_ids)\n",
        "                logits = outputs.logits[0, -1, :]\n",
        "            \n",
        "            probs = torch.softmax(logits, dim=-1)\n",
        "            next_token = torch.multinomial(probs, num_samples=1)\n",
        "            generated_ids = torch.cat([generated_ids, next_token.unsqueeze(0)], dim=-1)\n",
        "            \n",
        "            if next_token.item() == self.tokenizer.eos_token_id:\n",
        "                break\n",
        "        \n",
        "        answer = self.tokenizer.decode(generated_ids[0, initial_len:], skip_special_tokens=True)\n",
        "        gen_time = time.time() - start_time\n",
        "        \n",
        "        return answer, retrieval_positions, gen_time\n",
        "\n",
        "\n",
        "class QueryOnlyGenerator:\n",
        "    \"\"\"Baseline: Single upfront retrieval based on query only.\"\"\"\n",
        "    \n",
        "    def __init__(self, model, tokenizer, retriever, max_gen_tokens=200):\n",
        "        self.model = model\n",
        "        self.tokenizer = tokenizer\n",
        "        self.retriever = retriever\n",
        "        self.max_gen_tokens = max_gen_tokens\n",
        "    \n",
        "    def generate(self, query: str) -> Tuple[str, List[int], float]:\n",
        "        \"\"\"Generate with single upfront retrieval.\"\"\"\n",
        "        start_time = time.time()\n",
        "        \n",
        "        # Single retrieval based on query\n",
        "        results = self.retriever.retrieve(query, top_k=2)\n",
        "        context = '\\n'.join([r['content'][:500] for r in results])\n",
        "        \n",
        "        prompt = f\"Context:\\n{context}\\n\\nQuestion: {query}\\nAnswer:\"\n",
        "        input_ids = self.tokenizer.encode(prompt, return_tensors='pt', \n",
        "                                          truncation=True, max_length=2048).to(self.model.device)\n",
        "        \n",
        "        with torch.no_grad():\n",
        "            outputs = self.model.generate(\n",
        "                input_ids,\n",
        "                max_new_tokens=self.max_gen_tokens,\n",
        "                pad_token_id=self.tokenizer.eos_token_id,\n",
        "                do_sample=True,\n",
        "                temperature=0.7\n",
        "            )\n",
        "        \n",
        "        answer = self.tokenizer.decode(outputs[0, input_ids.shape[1]:], skip_special_tokens=True)\n",
        "        gen_time = time.time() - start_time\n",
        "        \n",
        "        return answer, [0], gen_time\n",
        "\n",
        "\n",
        "class NoRetrievalGenerator:\n",
        "    \"\"\"Lower bound: No retrieval at all.\"\"\"\n",
        "    \n",
        "    def __init__(self, model, tokenizer, max_gen_tokens=200):\n",
        "        self.model = model\n",
        "        self.tokenizer = tokenizer\n",
        "        self.max_gen_tokens = max_gen_tokens\n",
        "    \n",
        "    def generate(self, query: str) -> Tuple[str, List[int], float]:\n",
        "        \"\"\"Generate without any retrieval.\"\"\"\n",
        "        start_time = time.time()\n",
        "        \n",
        "        prompt = f\"Question: {query}\\nAnswer:\"\n",
        "        input_ids = self.tokenizer.encode(prompt, return_tensors='pt').to(self.model.device)\n",
        "        \n",
        "        with torch.no_grad():\n",
        "            outputs = self.model.generate(\n",
        "                input_ids,\n",
        "                max_new_tokens=self.max_gen_tokens,\n",
        "                pad_token_id=self.tokenizer.eos_token_id,\n",
        "                do_sample=True,\n",
        "                temperature=0.7\n",
        "            )\n",
        "        \n",
        "        answer = self.tokenizer.decode(outputs[0, input_ids.shape[1]:], skip_special_tokens=True)\n",
        "        gen_time = time.time() - start_time\n",
        "        \n",
        "        return answer, [], gen_time\n",
        "\n",
        "\n",
        "print(\"Ablation baseline classes defined:\")\n",
        "print(\"  - RandomRetrievalGenerator\")\n",
        "print(\"  - FixedIntervalGenerator\") \n",
        "print(\"  - QueryOnlyGenerator\")\n",
        "print(\"  - NoRetrievalGenerator\")\n",
        "print(\"\\nCCE-Spike will use the existing RealCCEMultiHopRetriever (best method from main evaluation)\")"
    ]
})

# Cell 3: Run Ablation Study using ACTUAL Real CCE
ABLATION_CELLS.append({
    'cell_type': 'code',
    'execution_count': None,
    'metadata': {},
    'outputs': [],
    'source': [
        "# Run Ablation Study\n",
        "# Uses ACTUAL RealCCEMultiHopRetriever for CCE-Spike (not a simplified version)\n",
        "\n",
        "from sentence_transformers import SentenceTransformer\n",
        "from sklearn.metrics.pairwise import cosine_similarity\n",
        "\n",
        "# Use the ACTUAL Real CCE retriever from the main evaluation\n",
        "# This is CCEQueryPlusTopKRetriever which showed best results\n",
        "real_cce_for_ablation = real_cce_retrievers['cce_query_plus_topk']\n",
        "\n",
        "# Initialize baseline generators\n",
        "random_gen = RandomRetrievalGenerator(model, tokenizer, retriever, max_gen_tokens=150)\n",
        "fixed_gen = FixedIntervalGenerator(model, tokenizer, retriever, max_gen_tokens=150)\n",
        "query_gen = QueryOnlyGenerator(model, tokenizer, retriever, max_gen_tokens=150)\n",
        "no_ret_gen = NoRetrievalGenerator(model, tokenizer, max_gen_tokens=150)\n",
        "\n",
        "# Similarity model\n",
        "sim_model = SentenceTransformer('all-MiniLM-L6-v2')\n",
        "\n",
        "def compute_similarity(answer: str, ground_truth: str) -> float:\n",
        "    if not answer or not ground_truth:\n",
        "        return 0.0\n",
        "    emb1 = sim_model.encode([answer])\n",
        "    emb2 = sim_model.encode([ground_truth])\n",
        "    return float(cosine_similarity(emb1, emb2)[0][0])\n",
        "\n",
        "# Run ablation\n",
        "ablation_results = []\n",
        "NUM_RANDOM_SEEDS = 5\n",
        "\n",
        "print(\"Running Ablation Study\")\n",
        "print(\"=\" * 70)\n",
        "print(\"CCE-Spike uses: RealCCEMultiHopRetriever (cce_query_plus_topk)\")\n",
        "print(\"=\" * 70)\n",
        "\n",
        "for i, example in enumerate(test_examples[:5]):\n",
        "    print(f\"\\nExample {i+1}/5: {example.query[:50]}...\")\n",
        "    \n",
        "    # 1. CCE-Spike using ACTUAL Real CCE implementation\n",
        "    start = time.time()\n",
        "    cce_result = real_cce_for_ablation.retrieve(example.query)\n",
        "    \n",
        "    # Generate answer with retrieved context\n",
        "    if cce_result.num_hops > 0 and cce_result.retrieved_content:\n",
        "        prompt = f\"Context:\\n{cce_result.retrieved_content}\\n\\nQuestion: {example.query}\\nAnswer:\"\n",
        "    else:\n",
        "        prompt = f\"Question: {example.query}\\nAnswer:\"\n",
        "    \n",
        "    inputs = tokenizer(prompt, return_tensors='pt', truncation=True, max_length=2048).to(model.device)\n",
        "    with torch.no_grad():\n",
        "        outputs = model.generate(**inputs, max_new_tokens=150, pad_token_id=tokenizer.eos_token_id)\n",
        "    spike_answer = tokenizer.decode(outputs[0][inputs['input_ids'].shape[1]:], skip_special_tokens=True)\n",
        "    spike_time = time.time() - start\n",
        "    spike_sim = compute_similarity(spike_answer, example.ground_truth_answer)\n",
        "    num_retrievals = cce_result.num_hops\n",
        "    \n",
        "    # Get retrieval positions from trace\n",
        "    spike_positions = []\n",
        "    if cce_result.trace:\n",
        "        for hop in cce_result.trace:\n",
        "            if 'token_position' in hop:\n",
        "                spike_positions.append(hop['token_position'])\n",
        "    \n",
        "    ablation_results.append({\n",
        "        'example_id': example.id,\n",
        "        'method': 'cce_spike',\n",
        "        'answer': spike_answer,\n",
        "        'similarity': spike_sim,\n",
        "        'num_retrievals': num_retrievals,\n",
        "        'positions': spike_positions,\n",
        "        'time': spike_time\n",
        "    })\n",
        "    print(f\"  CCE-Spike (Real CCE): sim={spike_sim:.3f}, retrievals={num_retrievals}\")\n",
        "    \n",
        "    # 2. Random (multiple seeds, match retrieval count)\n",
        "    target_retrievals = max(1, num_retrievals)\n",
        "    for seed in range(NUM_RANDOM_SEEDS):\n",
        "        random_answer, random_positions, random_time = random_gen.generate(\n",
        "            example.query, num_retrievals=target_retrievals, seed=seed\n",
        "        )\n",
        "        random_sim = compute_similarity(random_answer, example.ground_truth_answer)\n",
        "        \n",
        "        ablation_results.append({\n",
        "            'example_id': example.id,\n",
        "            'method': 'random',\n",
        "            'answer': random_answer,\n",
        "            'similarity': random_sim,\n",
        "            'num_retrievals': len(random_positions),\n",
        "            'positions': random_positions,\n",
        "            'time': random_time,\n",
        "            'seed': seed\n",
        "        })\n",
        "    \n",
        "    random_avg = np.mean([r['similarity'] for r in ablation_results \n",
        "                          if r['example_id'] == example.id and r['method'] == 'random'])\n",
        "    print(f\"  Random (avg of {NUM_RANDOM_SEEDS}): sim={random_avg:.3f}\")\n",
        "    \n",
        "    # 3. Fixed-Interval\n",
        "    interval = max(30, 150 // target_retrievals)\n",
        "    fixed_answer, fixed_positions, fixed_time = fixed_gen.generate(\n",
        "        example.query, interval=interval, max_retrievals=target_retrievals\n",
        "    )\n",
        "    fixed_sim = compute_similarity(fixed_answer, example.ground_truth_answer)\n",
        "    \n",
        "    ablation_results.append({\n",
        "        'example_id': example.id,\n",
        "        'method': 'fixed_interval',\n",
        "        'answer': fixed_answer,\n",
        "        'similarity': fixed_sim,\n",
        "        'num_retrievals': len(fixed_positions),\n",
        "        'positions': fixed_positions,\n",
        "        'time': fixed_time\n",
        "    })\n",
        "    print(f\"  Fixed-Interval: sim={fixed_sim:.3f}\")\n",
        "    \n",
        "    # 4. Query-Only\n",
        "    query_answer, query_positions, query_time = query_gen.generate(example.query)\n",
        "    query_sim = compute_similarity(query_answer, example.ground_truth_answer)\n",
        "    \n",
        "    ablation_results.append({\n",
        "        'example_id': example.id,\n",
        "        'method': 'query_only',\n",
        "        'answer': query_answer,\n",
        "        'similarity': query_sim,\n",
        "        'num_retrievals': 1,\n",
        "        'positions': [0],\n",
        "        'time': query_time\n",
        "    })\n",
        "    print(f\"  Query-Only: sim={query_sim:.3f}\")\n",
        "    \n",
        "    # 5. No-Retrieval\n",
        "    no_ret_answer, _, no_ret_time = no_ret_gen.generate(example.query)\n",
        "    no_ret_sim = compute_similarity(no_ret_answer, example.ground_truth_answer)\n",
        "    \n",
        "    ablation_results.append({\n",
        "        'example_id': example.id,\n",
        "        'method': 'no_retrieval',\n",
        "        'answer': no_ret_answer,\n",
        "        'similarity': no_ret_sim,\n",
        "        'num_retrievals': 0,\n",
        "        'positions': [],\n",
        "        'time': no_ret_time\n",
        "    })\n",
        "    print(f\"  No-Retrieval: sim={no_ret_sim:.3f}\")\n",
        "\n",
        "print(\"\\n\" + \"=\" * 70)\n",
        "print(\"Ablation study complete!\")"
    ]
})

# Cell 4: Analyze Results (same as before but with clearer labels)
ABLATION_CELLS.append({
    'cell_type': 'code',
    'execution_count': None,
    'metadata': {},
    'outputs': [],
    'source': [
        "# Analyze ablation results\n",
        "import pandas as pd\n",
        "\n",
        "df_ablation = pd.DataFrame(ablation_results)\n",
        "\n",
        "def bootstrap_ci(data, n_bootstrap=1000, ci=95):\n",
        "    data = np.array(data)\n",
        "    data = data[~np.isnan(data)]\n",
        "    if len(data) < 2:\n",
        "        mean = np.mean(data) if len(data) > 0 else 0\n",
        "        return mean, mean, mean\n",
        "    boot_means = [np.mean(np.random.choice(data, size=len(data), replace=True)) \n",
        "                  for _ in range(n_bootstrap)]\n",
        "    return np.mean(data), np.percentile(boot_means, 2.5), np.percentile(boot_means, 97.5)\n",
        "\n",
        "print(\"\\n\" + \"=\" * 70)\n",
        "print(\"ABLATION STUDY RESULTS\")\n",
        "print(\"=\" * 70)\n",
        "print(\"\\nCCE-Spike uses ACTUAL RealCCEMultiHopRetriever (cce_query_plus_topk)\")\n",
        "print(\"\\nAnswer Similarity by Retrieval Strategy (95% Bootstrap CI):\")\n",
        "print(\"-\" * 70)\n",
        "\n",
        "methods_order = ['cce_spike', 'random', 'fixed_interval', 'query_only', 'no_retrieval']\n",
        "method_labels = {\n",
        "    'cce_spike': 'CCE-Spike (Real CCE)',\n",
        "    'random': 'Random Timing',\n",
        "    'fixed_interval': 'Fixed-Interval',\n",
        "    'query_only': 'Query-Only (Upfront)',\n",
        "    'no_retrieval': 'No Retrieval'\n",
        "}\n",
        "\n",
        "ablation_summary = []\n",
        "for method in methods_order:\n",
        "    scores = df_ablation[df_ablation['method'] == method]['similarity'].values\n",
        "    mean, ci_low, ci_high = bootstrap_ci(scores)\n",
        "    avg_ret = df_ablation[df_ablation['method'] == method]['num_retrievals'].mean()\n",
        "    \n",
        "    ablation_summary.append({\n",
        "        'Method': method_labels[method],\n",
        "        'Similarity': mean,\n",
        "        'CI_Low': ci_low,\n",
        "        'CI_High': ci_high,\n",
        "        'Avg_Retrievals': avg_ret\n",
        "    })\n",
        "    print(f\"{method_labels[method]:25s}: {mean:.3f} [{ci_low:.3f}, {ci_high:.3f}]  ({avg_ret:.1f} retrievals)\")\n",
        "\n",
        "df_ablation_summary = pd.DataFrame(ablation_summary)\n",
        "\n",
        "# Key comparisons\n",
        "print(\"\\n\" + \"-\" * 70)\n",
        "print(\"KEY COMPARISONS (same retrieval budget):\")\n",
        "print(\"-\" * 70)\n",
        "\n",
        "spike_scores = df_ablation[df_ablation['method'] == 'cce_spike']['similarity'].values\n",
        "random_scores = df_ablation[df_ablation['method'] == 'random']['similarity'].values\n",
        "\n",
        "spike_mean = np.mean(spike_scores)\n",
        "random_mean = np.mean(random_scores)\n",
        "diff = spike_mean - random_mean\n",
        "\n",
        "print(f\"\\n*** CCE-Spike vs Random (CRITICAL TEST) ***\")\n",
        "print(f\"    CCE-Spike: {spike_mean:.3f}\")\n",
        "print(f\"    Random:    {random_mean:.3f}\")\n",
        "print(f\"    Diff:      {diff:+.3f}\")\n",
        "\n",
        "if diff > 0.05:\n",
        "    print(f\"\\n    ✓ CCE-Spike BEATS Random → ENTROPY SPIKES ARE MEANINGFUL\")\n",
        "elif diff > 0:\n",
        "    print(f\"\\n    ~ CCE-Spike slightly better → weak evidence for spikes\")\n",
        "elif diff > -0.05:\n",
        "    print(f\"\\n    ✗ CCE-Spike ≈ Random → spikes may be NOISE\")\n",
        "else:\n",
        "    print(f\"\\n    ✗ CCE-Spike WORSE than Random → spikes are MISLEADING\")"
    ]
})

# Cell 5: Visualization (same as before)
ABLATION_CELLS.append({
    'cell_type': 'code',
    'execution_count': None,
    'metadata': {},
    'outputs': [],
    'source': [
        "# Visualize ablation results\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
        "\n",
        "# Plot 1: Overall comparison\n",
        "ax1 = axes[0]\n",
        "methods = df_ablation_summary['Method'].tolist()\n",
        "sims = df_ablation_summary['Similarity'].tolist()\n",
        "ci_lows = df_ablation_summary['CI_Low'].tolist()\n",
        "ci_highs = df_ablation_summary['CI_High'].tolist()\n",
        "errors = [[s - l for s, l in zip(sims, ci_lows)],\n",
        "          [h - s for s, h in zip(sims, ci_highs)]]\n",
        "\n",
        "colors = ['#2ecc71', '#3498db', '#9b59b6', '#f39c12', '#e74c3c']\n",
        "bars = ax1.bar(range(len(methods)), sims, yerr=errors, capsize=5,\n",
        "               color=colors, edgecolor='black', linewidth=1.2)\n",
        "ax1.set_xticks(range(len(methods)))\n",
        "ax1.set_xticklabels(methods, rotation=45, ha='right', fontsize=9)\n",
        "ax1.set_ylabel('Answer Similarity')\n",
        "ax1.set_title('Ablation: Is Entropy Spike a Valid Trigger?\\n(95% Bootstrap CI)')\n",
        "ax1.set_ylim(0, 1)\n",
        "ax1.axhline(y=sims[0], color='#2ecc71', linestyle='--', alpha=0.5)\n",
        "\n",
        "for bar, sim in zip(bars, sims):\n",
        "    ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.02,\n",
        "             f'{sim:.3f}', ha='center', va='bottom', fontsize=10)\n",
        "\n",
        "# Plot 2: Per-example Spike vs Random\n",
        "ax2 = axes[1]\n",
        "example_ids = df_ablation[df_ablation['method'] == 'cce_spike']['example_id'].unique()\n",
        "\n",
        "spike_by_ex = [df_ablation[(df_ablation['example_id'] == eid) & \n",
        "                           (df_ablation['method'] == 'cce_spike')]['similarity'].values[0]\n",
        "               for eid in example_ids]\n",
        "random_by_ex = [df_ablation[(df_ablation['example_id'] == eid) & \n",
        "                            (df_ablation['method'] == 'random')]['similarity'].mean()\n",
        "                for eid in example_ids]\n",
        "\n",
        "x = np.arange(len(example_ids))\n",
        "width = 0.35\n",
        "ax2.bar(x - width/2, spike_by_ex, width, label='CCE-Spike', color='#2ecc71')\n",
        "ax2.bar(x + width/2, random_by_ex, width, label='Random', color='#3498db')\n",
        "ax2.set_ylabel('Answer Similarity')\n",
        "ax2.set_title('Per-Example: CCE-Spike vs Random')\n",
        "ax2.set_xticks(x)\n",
        "ax2.set_xticklabels([f'Ex {i+1}' for i in range(len(example_ids))])\n",
        "ax2.legend()\n",
        "ax2.set_ylim(0, 1)\n",
        "\n",
        "spike_wins = sum(s > r for s, r in zip(spike_by_ex, random_by_ex))\n",
        "ax2.set_xlabel(f'Spike wins: {spike_wins}/{len(example_ids)} examples')\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.savefig('ablation_study_results.png', dpi=150, bbox_inches='tight')\n",
        "plt.show()\n",
        "\n",
        "print(f\"\\nSpike wins on {spike_wins}/{len(example_ids)} examples\")"
    ]
})

# Cell 6: Conclusion
ABLATION_CELLS.append({
    'cell_type': 'markdown',
    'metadata': {},
    'source': [
        "## Ablation Study Conclusions\\n",
        "\\n",
        "### The Critical Test\\n",
        "\\n",
        "**CCE-Spike vs Random** with same number of retrievals:\\n",
        "- If Spike > Random → Entropy spikes identify **meaningful** retrieval moments\\n",
        "- If Spike ≈ Random → Spikes are **noise** (timing doesn't matter)\\n",
        "- If Spike < Random → Spikes are **misleading** (wrong timing)\\n",
        "\\n",
        "### Interpretation\\n",
        "\\n",
        "| Result | Evidence Level |\\n",
        "|--------|---------------|\\n",
        "| Spike >> Random (+0.10) | Strong: spikes are meaningful |\\n",
        "| Spike > Random (+0.05) | Moderate: spikes help |\\n",
        "| Spike ≈ Random (±0.05) | None: spikes are noise |\\n",
        "| Spike < Random | Negative: spikes are harmful |\\n",
        "\\n",
        "### Note\\n",
        "This ablation uses the **actual** RealCCEMultiHopRetriever implementation,\\n",
        "not a simplified version, ensuring the comparison is fair."
    ]
})


def fix_ablation_in_notebook():
    """Replace the simplified ablation with the proper one using Real CCE."""
    print("Fixing ablation study to use actual Real CCE implementation")
    print("=" * 60)

    with open('Week8_Comprehensive_Evaluation.ipynb', 'r', encoding='utf-8') as f:
        nb = json.load(f)

    # Find and remove existing ablation cells
    cells_to_remove = []
    for i, cell in enumerate(nb['cells']):
        source = ''.join(cell.get('source', []))
        if ('class AblationStudy' in source or
            'Ablation Study: Is Entropy Spike' in source or
            'ablation_results' in source and 'RandomRetrievalGenerator' not in source):
            cells_to_remove.append(i)

    # Remove in reverse order to maintain indices
    for i in sorted(cells_to_remove, reverse=True):
        print(f"Removing old ablation cell at index {i}")
        nb['cells'].pop(i)

    # Find insertion point (after comparison table export)
    insert_idx = len(nb['cells']) - 2
    for i, cell in enumerate(nb['cells']):
        source = ''.join(cell.get('source', []))
        if "'comparison_table':" in source and 'to_dict' in source:
            insert_idx = i + 1
            break

    # Insert new ablation cells
    for j, cell in enumerate(ABLATION_CELLS):
        if isinstance(cell.get('source'), list):
            cell['source'] = [line if line.endswith('\n') else line + '\n'
                             for line in cell['source']]
            if cell['source']:
                cell['source'][-1] = cell['source'][-1].rstrip('\n')

        if cell['cell_type'] == 'code':
            cell['execution_count'] = None
            cell['outputs'] = []

        nb['cells'].insert(insert_idx + j, cell)

    with open('Week8_Comprehensive_Evaluation.ipynb', 'w', encoding='utf-8') as f:
        json.dump(nb, f, indent=1)

    print(f"\nAdded {len(ABLATION_CELLS)} fixed ablation cells at index {insert_idx}")
    print("\nKey change: CCE-Spike now uses actual RealCCEMultiHopRetriever")
    print("            (cce_query_plus_topk), not a simplified version")

if __name__ == '__main__':
    import os
    os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    fix_ablation_in_notebook()
